// Gerotor pair + bearing harness — parametric, eccentricity derived from the math.

// See gerotor_design.md for design reasoning. Architecture (Arrangement 2): both
// rotors journaled on fixed parallel axes offset by `e`, belt-timed at (N+1):N.
// The outer rotor rides a LARGE-ID bearing whose ID clears the inner rotor's
// orbit; the inner rotor rides a small shaft + bearing. Precision lives in the
// bore spacing (= e) on a reprintable plate, which is the printer's good (XY) axis.
//
// ---- Profile theory ---------
// Each member is a trochoid generated by a point at radius `r2` on a circle of
// radius `r1` (rolling relation a2 = a1 * r1/r2). The two members of a conjugate
// gerotor share the SAME generating radius `r2`; they differ only in tooth count
// (outer No = N+1, inner N) and base radius `r1`.
//
// Original relation:  r2 = r1 / (n - 1)
//   Outer: n = No = N+1, r1 = ro          -> r2 = ro / N
//   Inner: n = N,        r1 = ro - e       -> r2 = (ro - e) / (N - 1)
//
// For the two r2 to match (the condition for a sealing conjugate pair), and for
// the offset to equal that shared r2, the eccentricity is:
//
//       e = r2 = ro / N
//
// so e is DERIVED from rotor size `ro` and lobe count N, not a free parameter.
// For N=3, ro=30  ->  e = 10 mm  (matches the original; large e is real and
// correct at low lobe count). Inner base radius is then ro - e.
// ---------------------------------------------------------------------------

/* [Rotor] */
// Inner rotor tooth count. Outer = N + 1.
N    = 3;
// Outer member base radius `r1`. Scale this for displacement.
ro   = 30;     // mm
// Tip-rounding / pin radius (offset applied to the raw trochoid).
pinOut = 1.5;  // mm, outer pocket rounding
pinIn  = 1.2;  // mm, inner lobe rounding

/* [Build] */
h        = 100;   // rotor height (mm)
twist    = 0;     // total helical twist over height (deg); see design notes
fn       = 256;   // profile resolution (points around the trochoid)

/* [Bearing harness] */
axialGap  = 0.15;  // mm, target rotor-to-plate clearance (set by shims, not Z)
// Bottom plate is thick: must fit both bearings plus blind kidney pockets (≥ portID
// deep) plus a solid floor — prevents any through-leak and damps whistle.
botPlateT = 28;
wall      = 4;     // housing wall around the outer bearing (mm)
// Inner shaft bearing (default 608: 8 ID / 22 OD / 7 W). Edit to a sourced part.
innB_id = 8;  innB_od = 22; innB_w = 7;
// Outer LARGE-ID bearing width; ID/OD are derived below from the orbit envelope.
outB_w  = 7;
// Top plate only needs to seat the outer bearing + shaft clearance — no ports.
topPlateT = outB_w + 4;  // just bearing width + a little wall each side

/* [Labyrinth seal] */
// Triangular (V-groove) circumferential grooves on the outer rotor OD.
// 45° flanks (width = 2×depth) make each groove self-supporting on FDM without supports.
// Grooves are clustered at the bottom end of the mesh zone where leakage pressure is highest.
// Set labN = 0 to disable.
labN     = 8;    // number of grooves
labDepth = 0.6;  // groove depth (mm); width = 2×depth for 45° flanks
labPitch = 1.8;  // centre-to-centre spacing (mm); keep ≥ 2×labDepth to leave a land

/* [Ports] */
portID   = 15;   // hose inner Ø to match (mm) — see design_constraints 
portWall = 3;    // port spout wall thickness (mm)
portLen  = 30;   // spout duct length (mm); ≥ portID for smooth entry (no whistle)
// Kidney ports through the BOTTOM plate, flanking the FIXED MESH SEAL at the top
// (90° = +y = the shaft-offset direction). The mesh seal is the stationary divider
// between intake and outlet — see gerotor_design.md (Pocket sealing section).
//   land = 10° total (5° each side of the 90° seal)
//   each kidney = 100° wide
//   intake centre = 90 + 5 + 50 = 145°  spans  95° → 195°
//   outlet centre = 90 - 5 - 50 =  35°  spans -15° → 85°  (= 345° → 85°)
//   bottom land ≈ 195° → 345° = 150° — generously separates the two far ends
intakeMid  = 140;  // deg, centre of intake kidney
outletMid  = 40;   // deg, centre of outlet kidney
portArc    = 90;  // deg, angular width of each kidney
// portRout/portRin (kidney slot radii) are derived after `e` — see derived section.

/* [Drive] */
// GT2 belt teeth are printed directly into the outer rotor OD at the top end,
// above the top bearing pocket. The belt pitch radius equals rotorOuterR.
// NOTE on ratio: rotors run at (N+1):N — the OUTER turns SLOWER. A single belt
// means the outer rotor (larger radius) drives the inner shaft pulley (smaller).
// innPulleyR is derived to give the correct (N+1):N speed ratio.
gt2RimH     = 12;   // axial height of the GT2 belt region on the outer rotor (mm)
innPulleyH  = 10;   // axial height of the inner shaft sourced pulley (mm)

/* [Output] */
// "pair"    : meshing rotor pair + bearings
// "harness" : rotors + bearing plates + bearings + inner shaft (3D check)
// "cross"   : horizontal cross-sections at several Z heights (frozen at t=0.2)
// "plate"   : the reprintable bearing plate alone (for printing/inspection)
mode = "cross"; // [pair, harness, cross, bottom_plate, top_plate]

/* [Cross-section] */
nSlices    = 5;     // number of cross-section slices
sliceT     = 1.0;   // thickness of each slice (mm)
// Rotation phase for cross-section mode (0..1). Pass via -D "tPhase=0.15".
// ($t cannot be set via -D; this regular variable substitutes for it.)
tPhase     = 0.2;

/* [Animation] */
rpm_demo = 1;    // arbitrary turns over the $t cycle, for visual checking

// ---- Derived (single source of truth) --------------------------------------
e   = ro / N;          // eccentricity == shared generating radius r2
ri  = ro - e;          // inner member base radius
rotorOuterR = ro + e + 5;   // outer rotor OD envelope (= housing cylinder radius)

// Kidney slot radii (need e): just inside the outer pockets, clearing the inner orbit.
portRout = ro + e;
portRin  = ro - e - 2;

// Outer bearing ID — shaft-clearance only (inner bearing is now outboard of the
// outer bearing, so only the inner *shaft* passes through the outer bearing centre).
// Required clear bore = 2*(e + innB_id/2 + slack), rounded up to a 5 mm step.
// This is much smaller than the old orbit-clearing size and stops the bearing
// intruding on the kidney annulus. See gerotor_design.md (Outer bearing ID section).
outB_id_req = 2 * (e + innB_id / 2 + 2);
outB_id     = ceil(outB_id_req / 5) * 5;
outB_od     = outB_id + 2 * 6;

// Inner shaft pulley pitch radius: (N+1):N ratio with the outer rotor OD.
innPulleyR  = rotorOuterR * N / (N + 1);

// Pocket depth: bearing width + a little clearance, used to size the kidney recess.
pocketDepth = outB_w + 2;
ductR       = (portRout + portRin )/ 2;

// ---- GT2 belt synchronisation -----------------------------------------------
// Outer rotor carries a printed GT2 5mm ring (additive teeth on OD — FDM friendly).
// Inner shaft uses a sourced GT2 5mm pulley.
// Tooth counts must satisfy the (N+1):N speed ratio exactly.
// GT2 5mm pitch diameter formula (from parametricPulley.scad tooth_spacing):
//   OD = teeth * 5 / pi - 2 * 0.5715  =  teeth * 5 / pi - 1.143
// Invert: teeth = (OD + 1.143) * pi / 5
// For rotorOuterR = 45 mm  →  (90 + 1.143) * pi / 5 ≈ 57.3
// Largest multiple of (N+1)=4 that is ≤ 57: 56   inner = 56*N/(N+1) = 42
outerGT2Teeth = 56;                        // printed on outer rotor
innerGT2Teeth = outerGT2Teeth * N / (N+1); // = 42 — standard sourced pulley
echo(outer_rotor_pulley_teeth = outerGT2Teeth,
     inner_shaft_pulley_teeth = innerGT2Teeth);

// GT2 5mm tooth geometry constants (parametricPulley.scad profile 14)
gt2_tooth_width       = 3.952;
gt2_additional_tooth_width = 0.2; // same default as parametricPulley.scad

// The toothed cylinder OD is rotorOuterR — the ring is flush with the rotor body,
// teeth cut inward exactly as pulley() does. tooth_distance_from_centre from pulley().
gt2_tooth_width_scale = (gt2_tooth_width + gt2_additional_tooth_width) / gt2_tooth_width;
gt2_tooth_r = sqrt(pow(rotorOuterR, 2) - pow((gt2_tooth_width + gt2_additional_tooth_width)/2, 2));

// GT2 tooth cutters — the set of tooth-shaped solids to subtract from the rotor OD.
// Mirrors the cutter loop in pulley(): each tooth placed at -gt2_tooth_r in Y so
// the tooth tip points toward the cylinder centre (inward = correct valley shape).
module gt2Ring(h_ring) {
    for (i = [1 : outerGT2Teeth])
        rotate([0, 0, i * (360 / outerGT2Teeth)])
            translate([0, -gt2_tooth_r, -h_ring/2 - 1])
                scale([gt2_tooth_width_scale, 1, 1])
                    gt2_5mm_tooth(h_ring);
}

use <primitives.scad>

// Displacement estimate (first-order; ignores pin rounding). See gerotor_design.md.
A_outer = polyArea(trochoid(N + 1, ro, fn));
A_inner = polyArea(trochoid(N, ri, fn));
dispChamber = A_outer - A_inner;          // mm^2 cross-section of voids
volPerRev   = dispChamber * h / 1000;     // cm^3 per inner revolution
flow2000    = volPerRev * 2000 / 1000;    // L/min at 2000 rpm (ideal)

echo(N = N, outer_teeth = N + 1, ro = ro, eccentricity_e = e, inner_base_ri = ri);
echo(A_outer_mm2 = A_outer, A_inner_mm2 = A_inner, voids_mm2 = dispChamber,
     vol_per_rev_cm3 = volPerRev, ideal_Lmin_at_2000rpm = flow2000);
echo(outer_bearing_ID_required = outB_id_req,
     outer_bearing_ID_chosen = outB_id, outer_bearing_OD = outB_od);

// ---- Rotor pair -------------------------------------------------------------
// member() extrudes a trochoid profile to an explicit height (not the global h).
module member(n, r1, grow, conv, ht, tw, seal = 0) {
    linear_extrude(ht, center = true, convexity = conv, twist = tw, slices = 20)
        difference() {
            offset(r = grow, $fn = 32)
                polygon(trochoid(n, r1, fn));
            if( seal > 0 ) {
                // one cutter per lobe tip
                // "labyrith seal" on the tip, can be filled when needed with hot glue or 3d pen for experimentation
                for (i = [0 : N-1]) {
                    rotate([0, 0,  i * 360/N])
                        translate([0, ri + pinIn + e - 0.2])  // approximate tip location
                            circle(d = seal, $fn = 16);
                }
            }
        }
}

// hRotor    : full outer rotor cylinder height (bearing pockets at each end)
// hPort     : short straight stub at each end — no profile cut, air flows axially
//             through the trochoid voids here to reach the kidney ports
// hMesh     : twisted meshing zone between the two stubs; same height for both rotors
// hInnerRotor: inner rotor matches hMesh minus axialGap clearance at each end
hRotor      = h;
hPort       = outB_w;
hMesh       = hRotor - 2 * hPort;
hInnerRotor = hMesh - 2 * axialGap;
tw = 15;   // total helical twist (deg) over hMesh

module outerRotor() {
    color("orange")
    rotate([0, 0, -(rpm_demo * 360 * $t) / (N + 1)])
    difference() {
        union() {
            // Top is closed - no leakage to outside there.
            // Bottom end has porting holes cut out below (not twisted).
            for (sz = [-1, 1])
                translate([0, 0, sz * (hMesh / 2 + hPort / 2)])
                    cylinder(r = rotorOuterR, h = hPort, center = true, $fn = 120);
            cylinder(r = rotorOuterR, h = hMesh, center = true, $fn = 120);
         }
        // Twisted meshing section.
        member(N + 1, ro, grow = pinOut, conv = 3, ht = hMesh, tw = tw * N);
       
        // Straight porting stubs at bottom end: plain cylinder, trochoid void open.
        // Air flows axially through the voids to the kidney ports.
        translate([0,0,-(hMesh + hPort)/2])
            member(N + 1, ro, grow = pinOut, conv = 3, ht = hPort + 0.1, tw = 0);
        // Bottom bearing pocket — covers the bottom stub end.
        translate([0, 0, -(hRotor / 2 - hPort / 2)])
            cylinder(d = outB_od + 0.2, h = hPort + 1, center = true, $fn = 96);
        // Top bearing pocket — symmetric.
        translate([0, 0,  (hRotor / 2 - hPort / 2)])
            cylinder(d = outB_od + 0.2, h = hPort + 1, center = true, $fn = 96);
        // GT2 tooth gaps — cut into the top stub surface.
        translate([0, 0, (hMesh / 2 + hPort / 2)])
            gt2Ring(gt2RimH);
        // Labyrinth seal grooves — triangular V-profile for 45° FDM printability.
        // First groove centred on the bottom edge of the rotor, stacking upward.
        // The bottom-most groove also bevels the sharp corner.
        if (labN > 0) {
            labZ0 = -hRotor / 2;   // rotor bottom edge
            for (i = [0 : labN - 1])
                translate([0, 0, labZ0 + i * labPitch])
                    rotate_extrude($fn = 120)
                        polygon([
                            [rotorOuterR - labDepth, 0],
                            [rotorOuterR + 0.01,  labDepth],
                            [rotorOuterR + 0.01, -labDepth],
                        ]);
        }
    }
}

module innerRotor() {
    color("yellow") 
    translate([0, e, 0])
    rotate([0, 0, -(rpm_demo * 360 * $t) / N])
    difference() {
        member(N, ri, grow = pinIn, conv = 4, ht = hInnerRotor, tw = tw * (N + 1), seal = 1);
        cylinder(d = innB_id+0.1, h = hInnerRotor + 1, center = true, $fn=180);
    }
}
module rotorPair() { outerRotor(); innerRotor(); }
module pair()      { rotorPair(); bearings(); }

// ---- Bearing harness (Arrangement 2) ---------------------------------------
// Ring proxy for a ball bearing (envelope only — races/balls omitted), centred at z.
module bearingProxy(id, od, w) {
    color([0.6, 0.6, 0.65])
    difference() {
        cylinder(d = od, h = w, center = true, $fn = 96);
        cylinder(d = id, h = w + 1, center = true, $fn = 96);
    }
}

// ---- Top plate --------------------------------------------------------------
// Mirror of the bottom plate architecture, minus kidneys and ports.
// Boss at centre (OD = outB_id) seats the outer bearing inner race, rotor grips
// the outer race. Inner shaft clearance hole at the offset axis.
module topPlate() {
    plateR = rotorOuterR + wall + e;
    bossH  = outB_w;
    color([0.85, 0.8, 0.7])
    difference() {
        union() {
            cylinder(r = plateR, h = topPlateT, center = true, $fn = 120);
            // Boss protrudes down into rotor space; inner race of top outer bearing slides onto it
            translate([0, 0, -(topPlateT / 2 + bossH / 2)])
                cylinder(d = outB_id, h = bossH, center = true, $fn = 120);
        }
        // Top inner bearing bore — blind pocket from outside (top) face, bearing presses in from above
        translate([0, e, topPlateT / 2 - (innB_w + 0.6) / 2])
            cylinder(d = innB_od + 0.1, h = innB_w + 0.8, center = true, $fn = 96);
        // Inner shaft clearance through full plate + boss
        translate([0, e, 0])
            cylinder(d = innB_id + 1, h = topPlateT + 2 * bossH + 2, center = true, $fn = 64);
    }
}

// ---- Bottom plate -----------------------------------------------------------
// Flat disc with a rotor-facing cavity that combines:
//   - Outer bearing protrusion at centre (outB_id): grey plate grips the ID (inner race);
//     orange rotor will grip the OD (outer race) via spokes — to be added later.
//   - Kidney arcs extending outward from the bearing bore at the same depth.
//   - Axial duct holes (portID) punching straight through at ductR.
//   - Inner bearing bore from outside face; shaft clearance all the way through.
// The cavity depth = pocketDepth; a solid floor remains on the outside face.
// pocketDepth and ductR are derived above (before use <primitives.scad>).

module bottomPlate() {
    plateR  = rotorOuterR + wall + e;
    // The plate provides a cylindrical BOSS (OD = outB_id) that the bearing inner
    // race slides onto (clearance/light press). The outer race is gripped by the
    // matching pocket in the outer rotor, so the rotor rides this bearing.
    // Air bypasses the bearing seat through the trochoid voids outside outB_od.
    bossH   = outB_w;         // boss height = bearing width 
    // Kidney recess: opens from the rotor face into the plate body by pocketDepth.
    recessH = pocketDepth + 2;  // +2 for cutter overshoot
    recessZ = botPlateT / 2 + 1 - recessH / 2;  // cutter centred so top = plate face+1

    color([0.85, 0.8, 0.7])
    difference() {
        union() {
            // Plate body
            cylinder(r = plateR, h = botPlateT, center = true, $fn = 120);
            // Boss protruding into rotor space from rotor-facing face (+botPlateT/2)
            translate([0, 0, botPlateT / 2 + bossH / 2])
                cylinder(d = outB_id, h = bossH, center = true, $fn = 120);
        }

        // Kidney arc recesses in the plate body (open on rotor-facing side)
        translate([0, 0, recessZ])
            kidneySolid(intakeMid, portArc, portRin, portRout, recessH);
        translate([0, 0, recessZ])
            kidneySolid(outletMid, portArc, portRin, portRout, recessH);

        // Axial duct holes straight through plate + boss
        for (mid = [intakeMid, outletMid])
            rotate([0, 0, mid])
            translate([ductR, 0, 0])
                cylinder(d = portID, h = botPlateT + bossH + 2, center = true, $fn = 48);

        // Inner bearing bore from outside face
        translate([0, e, -botPlateT / 2 + (innB_w + 0.5) / 2])
            cylinder(d = innB_od + 0.1, h = innB_w + 0.6, center = true, $fn = 96);

        // Inner shaft clearance through full plate
        translate([0, e, 0])
            cylinder(d = innB_id + 1, h = botPlateT + 2 * bossH + 2, center = true, $fn = 64);
    }
}


// ---- Bearings (shaft + bearing proxies) -------------------------------------
// Outer rotor rides two outer bearings: outer race in rotor pockets, inner race
// on plate bosses. Inner shaft has one bearing in the bottom plate outside face.
module bearings() {
    zBot     = hRotor / 2 + axialGap + botPlateT / 2;
    zTop     = hRotor / 2 + axialGap + topPlateT / 2;
    shaftBot = -(zBot + botPlateT / 2 + 5);
    shaftTop =   zTop + topPlateT / 2 + innPulleyH + 5;

    // Bottom outer bearing — inner race on bottom plate boss, outer race in rotor
    translate([0, 0, -(hRotor / 2 - outB_w / 2)])
        bearingProxy(outB_id, outB_od, outB_w);

    // Top outer bearing — inner race on top plate boss, outer race in rotor
    translate([0, 0,  (hRotor / 2 - outB_w / 2)])
        bearingProxy(outB_id, outB_od, outB_w);

    // Bottom inner bearing — recessed into the outside face of the bottom plate
    translate([0, e, -(zBot + botPlateT / 2) + innB_w / 2 + 0.5])
        bearingProxy(innB_id, innB_od, innB_w);

    // Top inner bearing — pressed in from outside (top) face of the top plate
    translate([0, e, zTop + topPlateT / 2 - (innB_w + 0.6) / 2])
        bearingProxy(innB_id, innB_od, innB_w);

    // Inner shaft + sourced pulley above the top plate, on the offset axis
    zPul = zTop + topPlateT / 2 + innPulleyH / 2 + 2;
    translate([0, e, 0]) {
        // Shaft
        color("yellow")
            translate([0, 0, (shaftTop + shaftBot) / 2])
                cylinder(d = innB_id, h = shaftTop - shaftBot, center = true, $fn = 48);
        // GT2 pulley proxy: belt rim + flanges + shaft bore.
        // Pitch radius = innPulleyR; rim height = innPulleyH; flanges add 1 mm each side.
        color("silver")
        translate([0, 0, zPul])
        rotate([0, 0, -(rpm_demo * 360 * $t) / N])
        difference() {
            union() {
                // Belt rim
                cylinder(r = innPulleyR, h = innPulleyH, center = true, $fn = 64);
                // Top and bottom flanges (prevent belt walking off)
                for (sz = [-1, 1])
                    translate([0, 0, sz * (innPulleyH / 2)])
                        cylinder(r = innPulleyR + 1, h = 1, center = true, $fn = 64);
            }
            // Shaft bore
            cylinder(d = innB_id + 0.2, h = innPulleyH + 4, center = true, $fn = 32);
        }
    }
}

module harness() {
    zBot = hRotor / 2 + axialGap + botPlateT / 2;
    zTop = hRotor / 2 + axialGap + topPlateT / 2;

    translate([0, 0, -zBot]) bottomPlate();
    translate([0, 0,  zTop]) topPlate();
    bearings();
}

// ---- Cross-section view -----------------------------------------------------
// Slices the rotor pair at evenly-spaced Z heights across the meshing zone,
// frozen at $t = 0.2. All slices are projected to Z=0 and spread along X so a
// single top-down view shows the full twist progression left to right.
module crossSections() {
    spacing = hMesh / (nSlices - 1);
    spread  = rotorOuterR * 2 + 8;
    centerX = -(nSlices - 1) * spread / 2;
    for (i = [0 : nSlices - 1]) {
        zCut = -hMesh / 2 + i * spacing;
        translate([centerX + i * spread, 0, 0])
        translate([0, 0, -zCut])   // project slice to Z=0
            intersection() {
                translate([0, 0, zCut])
                    cube([rotorOuterR * 4, rotorOuterR * 4, sliceT], center = true);
                let($t = tPhase) rotorPair();
            }
    }
}

// ---- Output dispatch --------------------------------------------------------
if      (mode == "top_plate")    topPlate();
else if (mode == "bottom_plate") bottomPlate();
else if (mode == "harness")      harness();
else if (mode == "cross")        crossSections();
else if (mode == "pair")         pair();
else {
    harness();
    pair();
}