// Gerotor pair — parametric, eccentricity derived from the profile math.
//
// Modernized from the 2014 original: removed deprecated assign() (-> let()),
// replaced the recursive point accumulator with a list comprehension, and lifted
// the eccentricity `e` out as a single derived value so it is no longer a
// hand-typed translate that can drift out of sync with the profile.
//
// See gerotor_design.md for design reasoning. Architecture: both rotors
// journaled on fixed parallel axes offset by `e`, belt-timed at (N+1):N.
//
// ---- Profile theory (faithful to the original, verified against it) ---------
// Each member is a trochoid generated by a point at radius `r2` on a circle of
// radius `r1` (rolling relation a2 = a1 * r1/r2). The two members of a conjugate
// gerotor share the SAME generating radius `r2`; they differ only in tooth count
// (outer No = N+1, inner N) and base radius `r1`.
//
// Original relation:  r2 = r1 / (n - 1)
//   Outer: n = No = N+1, r1 = ro          -> r2 = ro / N
//   Inner: n = N,        r1 = ro - e       -> r2 = (ro - e) / (N - 1)
//
// For the two r2 to match (the condition for a sealing conjugate pair), and for
// the offset to equal that shared r2, the eccentricity is:
//
//       e = r2 = ro / N
//
// so e is DERIVED from rotor size `ro` and lobe count N, not a free parameter.
// For N=3, ro=30  ->  e = 10 mm  (matches the original; large e is real and
// correct at low lobe count). Inner base radius is then ro - e.
// ---------------------------------------------------------------------------

/* [Rotor] */
// Inner rotor tooth count. Outer = N + 1.
N    = 3;
// Outer member base radius `r1`. Scale this for displacement.
ro   = 30;     // mm
// Tip-rounding / pin radius (offset applied to the raw trochoid).
pinOut = 1.5;  // mm, outer pocket rounding
pinIn  = 1.0;  // mm, inner lobe rounding

/* [Build] */
h        = 100;   // rotor height (mm)
twist    = 0;     // total helical twist over height (deg); see design notes
fn       = 256;   // profile resolution (points around the trochoid)

/* [Animation] */
rpm_demo = 20;    // arbitrary turns over the $t cycle, for visual checking

// ---- Derived (single source of truth) --------------------------------------
e   = ro / N;          // eccentricity == shared generating radius r2
ri  = ro - e;          // inner member base radius

// Shoelace area of a closed point list (mm^2). The cross-term list is summed by
// a dot product with a ones-vector (OpenSCAD has no built-in sum()).
function polyArea(p) =
    let (cross = [ for (i = [0 : len(p) - 1])
                     let (j = (i + 1) % len(p))
                     p[i].x * p[j].y - p[j].x * p[i].y ],
         ones  = [ for (i = [0 : len(p) - 1]) 1 ])
    abs(0.5 * (cross * ones));

// Displacement estimate: (outer pocket area - inner lobe area) is the gas
// volume trapped per chamber pair; over one inner revolution all N chambers
// sweep once, so volume/rev ~= (A_outer - A_inner) * h. This ignores the pin
// rounding offsets (small) and is a first-order estimate for comparing options.
A_outer = polyArea(trochoid(N + 1, ro, fn));
A_inner = polyArea(trochoid(N, ri, fn));
dispChamber = (A_outer - A_inner);              // mm^2 cross-section of voids
volPerRev   = dispChamber * h / 1000;           // cm^3 per inner revolution
flow2000    = volPerRev * 2000 / 1000;          // L/min at 2000 rpm (ideal)

echo(N = N, outer_teeth = N + 1, ro = ro, eccentricity_e = e, inner_base_ri = ri);
echo(A_outer_mm2 = A_outer, A_inner_mm2 = A_inner,
     voids_mm2 = dispChamber, vol_per_rev_cm3 = volPerRev,
     ideal_Lmin_at_2000rpm = flow2000);

// Trochoid point list, faithful to the original rtroch_b:
//   r2 = r1/(n-1);  a1 = i*360/steps;  a2 = a1 * r1/r2
//   p  = r1*[sin a1, cos a1] + r2*[-sin a2, cos a2]
function trochoid(n, r1, steps) =
    let (r2 = r1 / (n - 1))
    [ for (i = [0 : steps - 1])
        let (a1 = i * 360 / steps,
             a2 = a1 * r1 / r2)
        r1 * [sin(a1), cos(a1)] + r2 * [-sin(a2), cos(a2)]
    ];

module member(n, r1, grow, conv) {
    linear_extrude(h, center = true, convexity = conv, twist = twist)
        offset(r = grow, $fn = 32)
            polygon(trochoid(n, r1, fn));
}

// ---- Outer rotor (N+1 teeth), rotates about origin --------------------------
rotate([0, 0, -(rpm_demo * 360 * $t) / (N + 1)])
difference() {
    cylinder(r = ro + e + 5, center = true, h = h - 1);
    member(N + 1, ro, grow = pinOut, conv = 3);
}

// ---- Inner rotor (N teeth), rotates about an axis offset by e ---------------
color("yellow")
translate([0, e, 0])
rotate([0, 0, -(rpm_demo * 360 * $t) / N])
    member(N, ri, grow = pinIn, conv = 4);
