// Gerotor pair + bearing harness — parametric, eccentricity derived from the math.
//
// Modernized from the 2014 original: removed deprecated assign() (-> let()),
// replaced the recursive point accumulator with a list comprehension, and lifted
// the eccentricity `e` out as a single derived value so it is no longer a
// hand-typed translate that can drift out of sync with the profile.
//
// See gerotor_design.md for design reasoning. Architecture (Arrangement 2): both
// rotors journaled on fixed parallel axes offset by `e`, belt-timed at (N+1):N.
// The outer rotor rides a LARGE-ID bearing whose ID clears the inner rotor's
// orbit; the inner rotor rides a small shaft + bearing. Precision lives in the
// bore spacing (= e) on a reprintable plate, which is the printer's good (XY) axis.
//
// ---- Profile theory (faithful to the original, verified against it) ---------
// Each member is a trochoid generated by a point at radius `r2` on a circle of
// radius `r1` (rolling relation a2 = a1 * r1/r2). The two members of a conjugate
// gerotor share the SAME generating radius `r2`; they differ only in tooth count
// (outer No = N+1, inner N) and base radius `r1`.
//
// Original relation:  r2 = r1 / (n - 1)
//   Outer: n = No = N+1, r1 = ro          -> r2 = ro / N
//   Inner: n = N,        r1 = ro - e       -> r2 = (ro - e) / (N - 1)
//
// For the two r2 to match (the condition for a sealing conjugate pair), and for
// the offset to equal that shared r2, the eccentricity is:
//
//       e = r2 = ro / N
//
// so e is DERIVED from rotor size `ro` and lobe count N, not a free parameter.
// For N=3, ro=30  ->  e = 10 mm  (matches the original; large e is real and
// correct at low lobe count). Inner base radius is then ro - e.
// ---------------------------------------------------------------------------

/* [Rotor] */
// Inner rotor tooth count. Outer = N + 1.
N    = 3;
// Outer member base radius `r1`. Scale this for displacement.
ro   = 30;     // mm
// Tip-rounding / pin radius (offset applied to the raw trochoid).
pinOut = 1.5;  // mm, outer pocket rounding
pinIn  = 1.0;  // mm, inner lobe rounding

/* [Build] */
h        = 100;   // rotor height (mm)
twist    = 0;     // total helical twist over height (deg); see design notes
fn       = 256;   // profile resolution (points around the trochoid)

/* [Bearing harness] */
axialGap  = 0.15;  // mm, target rotor-to-plate clearance (set by shims, not Z)
// Bottom plate is thick: must fit both bearings plus blind kidney pockets (≥ portID
// deep) plus a solid floor — prevents any through-leak and damps whistle.
botPlateT = 28;
wall      = 4;     // housing wall around the outer bearing (mm)
// Inner shaft bearing (default 608: 8 ID / 22 OD / 7 W). Edit to a sourced part.
innB_id = 8;  innB_od = 22; innB_w = 7;
// Outer LARGE-ID bearing width; ID/OD are derived below from the orbit envelope.
outB_w  = 7;
// Top plate only needs to seat the outer bearing + shaft clearance — no ports.
topPlateT = outB_w + 4;  // just bearing width + a little wall each side

/* [Top bearing bridge] */
// The top inner bearing sits above the orange pulley and must be held by the FIXED
// world. A bridge (yoke) rises from the top plate on posts that clear the pulley OD,
// spans over it, and caps the inner bearing's outer race — screwed down.
bridgePostD = 8;   // diameter of the support posts (mm)
bridgeCapT  = 6;   // thickness of the bridge cap that holds the bearing (mm)
screwD      = 3;   // M3 cap screws

/* [Ports] */
portID   = 25;   // hose inner Ø to match (mm) — see design_constraints (25 mm tubing)
portWall = 3;    // port spout wall thickness (mm)
portLen  = 30;   // spout duct length (mm); ≥ portID for smooth entry (no whistle)
// Kidney ports through the BOTTOM plate, flanking the FIXED MESH SEAL at the top
// (90° = +y = the shaft-offset direction). The mesh seal is the stationary divider
// between intake and outlet — see gerotor_design.md (Pocket sealing section).
//   land = 10° total (5° each side of the 90° seal)
//   each kidney = 100° wide
//   intake centre = 90 + 5 + 50 = 145°  spans  95° → 195°
//   outlet centre = 90 - 5 - 50 =  35°  spans -15° → 85°  (= 345° → 85°)
//   bottom land ≈ 195° → 345° = 150° — generously separates the two far ends
intakeMid  = 140;  // deg, centre of intake kidney
outletMid  = 40;   // deg, centre of outlet kidney
portArc    = 90;  // deg, angular width of each kidney
// portRout/portRin (kidney slot radii) are derived after `e` — see derived section.

/* [Drive] */
// Integral printed pulley on the OUTER rotor (orange, one printed part with the
// rotor). The belt drives this directly; large diameter = forgiving printed teeth.
// NOTE on ratio: rotors must run at (N+1):N, i.e. the OUTER turns SLOWER. With a
// single shared belt that means the outer pulley must be the LARGER pitch radius
// and the inner the smaller, in the ratio (N+1):N. The proxy radii below are
// placeholders for fit only; real ratio comes from tooth counts. outPulleyR/
// innPulleyR are derived after rotorOuterR is known (see derived section).
outPulleyH  = 12;   // axial height of the outer pulley rim (mm)
innPulleyH  = 10;   // axial height of the inner sourced pulley (mm)
beltClear   = 3;    // axial gap between outer pulley and inner pulley region (mm)

/* [Output] */
// "pair"    : just the meshing rotor pair (default; fast to animate, top view)
// "harness" : rotors + bearing plates + bearings + inner shaft (3D check)
// "plate"   : the reprintable bearing plate alone (for printing/inspection)
mode = "pair"; // [pair, harness, bottom_plate, top_plate]

/* [Animation] */
rpm_demo = 20;    // arbitrary turns over the $t cycle, for visual checking

// ---- Derived (single source of truth) --------------------------------------
e   = ro / N;          // eccentricity == shared generating radius r2
ri  = ro - e;          // inner member base radius
rotorOuterR = ro + e + 5;   // outer rotor OD envelope (= housing cylinder radius)

// Kidney slot radii (need e): just inside the outer pockets, clearing the inner orbit.
portRout = ro - 1;
portRin  = ro - e - 2;

// Outer bearing ID — shaft-clearance only (inner bearing is now outboard of the
// outer bearing, so only the inner *shaft* passes through the outer bearing centre).
// Required clear bore = 2*(e + innB_id/2 + slack), rounded up to a 5 mm step.
// This is much smaller than the old orbit-clearing size and stops the bearing
// intruding on the kidney annulus. See gerotor_design.md (Outer bearing ID section).
outB_id_req = 2 * (e + innB_id / 2 + 2);
outB_id     = ceil(outB_id_req / 5) * 5;
outB_od     = outB_id + 2 * 6;

// Pulley pitch radii (proxy, fit-only). Ratio must be (N+1):N with the OUTER the
// larger. Anchor the outer pulley near the rotor OD and scale the inner down by
// the speed ratio so the proxy at least shows the correct relative sizes.
outPulleyR  = rotorOuterR;
innPulleyR  = outPulleyR * N / (N + 1);

use <primitives.scad>

// Displacement estimate (first-order; ignores pin rounding). See gerotor_design.md.
A_outer = polyArea(trochoid(N + 1, ro, fn));
A_inner = polyArea(trochoid(N, ri, fn));
dispChamber = A_outer - A_inner;          // mm^2 cross-section of voids
volPerRev   = dispChamber * h / 1000;     // cm^3 per inner revolution
flow2000    = volPerRev * 2000 / 1000;    // L/min at 2000 rpm (ideal)

echo(N = N, outer_teeth = N + 1, ro = ro, eccentricity_e = e, inner_base_ri = ri);
echo(A_outer_mm2 = A_outer, A_inner_mm2 = A_inner, voids_mm2 = dispChamber,
     vol_per_rev_cm3 = volPerRev, ideal_Lmin_at_2000rpm = flow2000);
echo(outer_bearing_ID_required = outB_id_req,
     outer_bearing_ID_chosen = outB_id, outer_bearing_OD = outB_od);

// ---- Rotor pair -------------------------------------------------------------
module member(n, r1, grow, conv) {
    linear_extrude(h, center = true, convexity = conv, twist = twist)
        offset(r = grow, $fn = 32)
            polygon(trochoid(n, r1, fn));
}
module outerRotor() {
    color("orange")
    rotate([0, 0, -(rpm_demo * 360 * $t) / (N + 1)])
    difference() {
        cylinder(r = rotorOuterR, center = true, h = h - 1);
        member(N + 1, ro, grow = pinOut, conv = 3);
    }
}

// Integral printed pulley on the outer rotor: a rim concentric with the outer
// rotor axis (origin), sitting just above the top bearing plate so the belt clears
// the housing. Modeled as a smooth rim (teeth omitted); it is connected to the orange
// printed rotor. The bore lets the inner shaft + its outboard bearing pass through.
module outerPulley() {
    color("orange")
    rotate([0, 0, -(rpm_demo * 360 * $t) / (N + 1)])
    difference() {
        union() {
            cylinder(r = outPulleyR, h = outPulleyH, center = true, $fn = 120);
            translate([0,0,-outPulleyH])
            cylinder(d = outB_id, h = outPulleyH, center = true, $fn = 120);
        }
        // central bore clears the offset inner shaft's full orbit. The bearing is above, so it doesn't conflict.
        cylinder(d = 2 * e + innB_id + 3, h = 3*outPulleyH + 1, center = true, $fn = 96);
    }
}
module innerRotor() {
    color("yellow")
    translate([0, e, 0])
    rotate([0, 0, -(rpm_demo * 360 * $t) / N])
        member(N, ri, grow = pinIn, conv = 4);
}
module rotorPair() { outerRotor(); innerRotor(); }

// ---- Bearing harness (Arrangement 2) ---------------------------------------
// Ring proxy for a ball bearing (envelope only — races/balls omitted), centred at z.
module bearingProxy(id, od, w) {
    color([0.6, 0.6, 0.65])
    difference() {
        cylinder(d = od, h = w, center = true, $fn = 96);
        cylinder(d = id, h = w + 1, center = true, $fn = 96);
    }
}

// ---- Top plate --------------------------------------------------------------
// Thin: seats the outer bearing (press-fit bore at origin) and has a shaft
// clearance hole at the offset axis. No ports, no inner bearing bore.
module topPlate() {
    color([0.85, 0.8, 0.7])
    difference() {
        cylinder(r = rotorOuterR + wall + e, h = topPlateT, center = true, $fn = 120);
        cylinder(d = outB_od + 0.1, h = topPlateT + 1, center = true, $fn = 120);
        translate([0, e, 0])
            cylinder(d = innB_id + 1, h = topPlateT + 1, center = true, $fn = 64);
    }
}

// ---- Bottom plate -----------------------------------------------------------
// Architecture (from your images):
//   ROTOR-FACING side: one unified cavity combining the outer bearing bore (centre)
//     + kidney arc pockets (flanking the bearing), all at depth `pocketDepth` from
//     the rotor face. The bearing sits in the centre of this cavity; kidneys extend
//     outward from it; grey plate grips bearing inner race, orange rotor presses on OD.
//   OUTSIDE face: solid except two axial duct holes (portID) at `ductR` and the
//     inner shaft clearance. Ducts connect the kidney pocket floor to the outside
//     for direct hose fitting — no radial bores, fully printable without support.
//   INNER bearing (yellow shaft): bore from outside face, shaft clearance through.

// Pocket depth from rotor face — must fit the outer bearing width.
pocketDepth = outB_w + 2;   // bearing width + 1 mm each side for shoulder
// Duct radius: at the outer edge of the kidney, clear of the inner bearing.
ductR = portRout + portID / 2 + 1;  // just outside the kidney outer edge

module bottomPlate() {
    plateR = rotorOuterR + wall + e;
    // Blind kidney pocket: a kidney solid sized to kidneyDepth, aligned to the
    // ROTOR-FACING face (top of the plate, z = +botPlateT/2 when centred).
    // Translate so its top face is flush with the rotor-facing face.
    // kidneyZ: centre of the cutter so its TOP is at botPlateT/2 + 1 (1 mm above
    // the rotor face — guaranteed to break through) and it extends kidneyDepth
    // into the plate, leaving a solid floor. Extra +2 on height, centre shifted up 1.
    kidneyZ = botPlateT / 2 + 1 - kidneyDepth / 2;

    color([0.85, 0.8, 0.7])
 
        difference() {
           union() {
            // Outer bearing bore — extends from ROTOR-FACING face (grey plate grips the ID /
            // inner race; orange rotor presses against the OD / outer race from outside).
            // Bore = outB_id + press clearance, depth = outB_w + 0.5, from rotor face.
            translate([0, 0, botPlateT / 2 + outB_w  / 2])
                cylinder(d = outB_id + 0.1, h = outB_w, center = true, $fn = 120);
            cylinder(r = plateR, h = botPlateT, center = true, $fn = 120);
           }
        // inner bearing bore at offset axis — from outside face
        translate([0, e, -botPlateT / 2 + (innB_w + 0.5) / 2])
            cylinder(d = innB_od + 0.1, h = innB_w + 0.6, center = true, $fn = 96);

        // inner shaft clearance through the full plate (shaft passes all the way through)
        translate([0, e, 0])
            cylinder(d = innB_id + 1, h = botPlateT + 2 * outB_w + 1, center = true, $fn = 64);

        // Blind kidney pockets — open on rotor-facing side, solid floor on outside.
        // kidneyZ is set so the cutter top is 1 mm above the rotor face (breaks
        // through cleanly); the floor stays solid toward the outside face.
        translate([0, 0, kidneyZ])
            kidneySolid(intakeMid, portArc, portRin, portRout, kidneyDepth + 2);
        translate([0, 0, kidneyZ])
            kidneySolid(outletMid, portArc, portRin, portRout, kidneyDepth + 2);

        // Axial duct: vertical cylinder straight through the plate, connecting the
        // kidney pocket to the outside face for direct hose fitting.
        // Placed at portRout - portID/2 - 1 so the duct sits fully within the kidney
        // annulus and clears the inner bearing region.
        ductR = portRout +3;
        for (mid = [intakeMid, outletMid])
            rotate([0, 0, mid])
            translate([ductR, 0, 0])
                cylinder(d = portID, h = botPlateT + 2, center = true, $fn = 48);
    }
}

// Bridge (yoke) that holds the top inner bearing from the FIXED world. Two posts
// rise from the top plate, just outside the orange pulley OD, and carry a cap that
// captures the top inner bearing's outer race over the offset axis. Screws shown as
// recessed holes in the cap. Grey = fixed.
module topBridge(zPlateTop, zInnBearTop) {
    // Posts sit on the offset axis line (y = e), placed left/right in x just outside
    // the orange pulley OD. The cap is a flat bar between them, centred over the top
    // inner bearing at (0, e), with a pocket that captures the bearing's outer race.
    postX  = outPulleyR + bridgePostD / 2 + 2;       // x of each post (clears pulley)
    postZ0 = zPlateTop + topPlateT / 2;              // post base = top face of plate
    capZ   = zInnBearTop;                            // cap centred on the top bearing
    postH  = capZ - postZ0;
    color([0.55, 0.55, 0.6]) {
        // two support posts, from the top plate up to the cap, flanking the bearing
        for (sx = [-1, 1])
            translate([sx * postX, e, postZ0 + postH / 2])
                cylinder(d = bridgePostD, h = postH, center = true, $fn = 32);

        // cap bar over the bearing, spanning between the two posts
        translate([0, e, capZ])
        difference() {
            hull() for (sx = [-1, 1])
                translate([sx * postX, 0, 0])
                    cylinder(d = bridgePostD + 4, h = bridgeCapT, center = true, $fn = 32);
            // pocket seating the bearing outer race (blind, opens downward)
            translate([0, 0, -bridgeCapT / 2 + 0.5])
                cylinder(d = innB_od + 0.3, h = bridgeCapT, center = true, $fn = 64);
            // shaft clearance up to the pulley
            cylinder(d = innB_id + 4, h = bridgeCapT + 2, center = true, $fn = 32);
            // M3 screw holes through the cap into each post
            for (sx = [-1, 1])
                translate([sx * postX, 0, 0])
                    cylinder(d = screwD, h = bridgeCapT + 2, center = true, $fn = 24);
        }
    }
}

// kidneySolid and wedgePrism are in primitives.scad (via use above).

// Ports are now axial ducts through the bottom plate — no radial spout needed.

// (bottomPlatePorts is now inlined into bottomPlate())

module harness() {
    rotorPair();
    zTop = h / 2 + axialGap + topPlateT / 2;       // top plate centre
    zBot = h / 2 + axialGap + botPlateT / 2;       // bottom plate centre
    zPlateTop = zTop;
    zOutPul   = zTop + topPlateT / 2 + outPulleyH / 2 + 1;

    // --- Top plate (thin) + outer bearing
    translate([0, 0,  zTop]) topPlate();
    translate([0, 0,  zTop]) bearingProxy(outB_id, outB_od, outB_w);

    // --- Bottom plate (thick) — seats both bearings, blind kidney pockets + axial ducts
    translate([0, 0, -zBot]) bottomPlate();

    // Outer bearing on the bottom plate: sits in its bore on the ROTOR-FACING side.
    // Bore opens from rotor face (zBotRotorFace = -zBot + botPlateT/2), bearing
    // centre is inset by outB_w/2 from that face.
    zBotRotorFace = -zBot + botPlateT / 2;
    zOutBearBot   = zBotRotorFace - (outB_w + 0.5) / 2;
    translate([0, 0, zOutBearBot])
        bearingProxy(outB_id, outB_od, outB_w);

    // Inner bearing proxy in bottom plate (outside face, offset axis)
    translate([0, e, -zBot - botPlateT/2 + (innB_w + 0.5)/2])
        bearingProxy(innB_id, innB_od, innB_w);

    // --- Orange outer rotor's integral pulley, just above the top plate.
    translate([0, 0, zOutPul]) outerPulley();

    // --- Yellow inner shaft + bearings + sourced pulley, on the offset axis.
    // The TOP inner bearing moves UP, outboard of the outer pulley, so it clears
    // the orange pulley. The inner sourced pulley sits beyond that bearing.
    zInnBearTop = zOutPul + outPulleyH / 2 + beltClear + innB_w / 2;
    zInnPul     = zInnBearTop + innB_w / 2 + innPulleyH / 2;
    shaftTop    = zInnPul + innPulleyH / 2 + 5;
    shaftBot    = -zBot - botPlateT / 2 - 5;

    translate([0, e, 0]) {
        // inner shaft spans from below the bottom plate to above the inner pulley
        color("yellow")
            translate([0, 0, (shaftTop + shaftBot) / 2])
                cylinder(d = innB_id, h = shaftTop - shaftBot, center = true, $fn = 48);
        // top inner bearing — outboard of the orange pulley
        translate([0, 0, zInnBearTop]) bearingProxy(innB_id, innB_od, innB_w);
        // inner sourced (non-printed) pulley — yellow, beyond the top bearing.
        // Note: it sits offset by e, so it does NOT share an axis with the outer
        // pulley; the belt spans the centre distance e between the two pitch radii.
        color("yellow")
        translate([0, 0, zInnPul])
            rotate([0, 0, -(rpm_demo * 360 * $t) / N])
            cylinder(r = innPulleyR, h = innPulleyH, center = true, $fn = 64);
    }

    // --- Top bridge that fixes the upper inner bearing to the world.
    topBridge(zPlateTop, zInnBearTop);

    // Ports are axial ducts — hose fittings attach directly to the outside plate face.
}

// ---- Output dispatch --------------------------------------------------------
if      (mode == "top_plate")    topPlate();
else if (mode == "bottom_plate") bottomPlate();
else if (mode == "harness")      harness();
else if (mode == "pair")         rotorPair();
else                             harness();